name: E2E Runners
on: workflow_dispatch
permissions:
  contents: read
jobs:
  non-latest-runners:
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-2025
          - windows-2019
          - macos-15
          - macos-13
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
      - run: tlmgr version
